# NOTE: when adding deps locally, you have to run the command:
# npm run prune-dev-npm
# docker-compose.yml
version: "3.8"

services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules_data:/app/node_modules
    ports:
      - 5555:5555
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
    depends_on:
      - db
    command: npm run start:dev

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data:
  node_modules_data: